project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - slides.qmd
    - skills.qmd

  resources:
    - CNAME
    - .nojekyll
    - portal-guide.html
    - mcnair.jpg
    - rice-business.jpg
    - currentdata.xlsx
    - lightGBM.pkl
    - session11A_interpretability.ipynb
    - session11B_neuralnetworks.ipynb
    - analyze_portfolios.ipynb
    - momentum.ipynb
    - momentum_current.ipynb
    - pdfs/Asness_Frazzini_Pedersen_RAS_2019.pdf
    - pdfs/Asness_Moskowitz_Pedersen_JF_2013.pdf
    - pdfs/Crane_Crotty_Umar_MS_2023.pdf
    - pdfs/Fama_French_JFE_2015.pdf
    - pdfs/Gu_Kelly_Xiu_RFS_2020.pdf
    - pdfs/Jegadeesh_Titman_ARFE_2011.pdf
    - pdfs/Kapadia_Ostdiek_Weston_Zekhnini_JFQA_2019.pdf
    - pdfs/Novy-Marx_Medhat_2025.pdf
    - pdfs/Frazzini_Israel_Moskowitz_2012.pdf
    - videos/Asness_Frazzini_Pedersen_RAS_2019.mp4
    - videos/Asness_Moskowitz_Pedersen_JF_2013.mp4
    - videos/Crane_Crotty_Umar_MS_2023.mp4
    - videos/Factor_Investing.mp4
    - videos/Fama_French_JFE_2015.mp4
    - videos/Gu_Kelly_Xiu_RFS_2020.mp4
    - videos/Jegadeesh_Titman_ARFE_2011.mp4
    - videos/Kapadia_Ostdiek_Weston_Zekhnini_JFQA_2019.mp4
    - videos/Novy-Marx_Medhat_2025.mp4
    - videos/Frazzini_Israel_Moskowitz_2012.mp4
    - slides/session01_slides.pdf
    - slides/session02_slides.pdf
    - slides/session03_slides.pdf
    - slides/session04_slides.pdf
    - slides/session05_slides.pdf
    - slides/session06_slides.pdf
    - slides/session07_slides.pdf
    - slides/session08_slides.pdf
    - slides/session09_slides.pdf
    - slides/session10_slides.pdf
    - slides/session11_slides.pdf
    - slides/session12_slides.pdf
    - slides/aiwg.pdf
                  
website:
  title: ""
  search: false  
  navbar:
    search: false
    title: MGMT 638
    file: index.qmd
    right:
        - text: Slides
          file: slides.qmd
          target: _blank
        - text: Data Guide
          href: https://portal-guide.rice-business.org
          target: _blank



   
format:
  html:
    theme:
      light: flatly
      dark: superhero
    link-external-newwindow: true
    
   






